### ISSUE TITLE
feat: Add `Client::new_without_greeting`

### ISSUE THREAD

**Issue by duesee** [duesee/imap-next#294]
To allow a minimal (and secure) STARTTLS implementation, we need a way to start a session that skips the greeting. This allows us to handle the STARTTLS prefix in any way we please and continue with an isolated IMAP session after STARTTLS was already handled. This allows to fully isolate the plaintext and encrypted phase.

### Implicit TLS

```imap
<--- TLS handshake --->
// Startpoint `Client::tls(...)`
S: * OK ... // Greeting
C: ...
```

### STARTTLS

```imap
S: * OK ...
C: A STARTTLS
S: A OK ...
<--- TLS handshake --->
// Startpoint `Client::tls_no_greeting(...)`
// No greeting per spec.
C: ...
```

Do we want this to be a constructor or an `Option`? Any naming suggestions?

**Comment by duesee** [comment]
The code to bring the stream up to the TLS transition could look like...

```rust
/// Bring a STARTTLS connection to the point where TLS is expected.
async fn do_starttls_prefix(stream: TcpStream) -> TcpStream {
    let reader = BufReader::new(stream);
    let mut lines = reader.lines();

    // Receive greeting.
    // Note: Greeting is *always* a single line.
    let _ = lines.next_line().await.unwrap();

    // Send STARTTLS command.
    lines.get_mut().write(b"A STARTTLS\r\n").await.unwrap();

    // Receive (and discard) all lines up until we get a
    // command completion result for our "A STARTTLS" command.
    loop {
        let line = lines.next_line().await.unwrap().unwrap();
        if line.starts_with("A ") {
            break;
        }
    }

    lines.into_inner().into_inner()
}
```

**Comment by soywod** [comment]
This should not be part of `imap-next` in my opinion, especially since TLS is out of its scope (thanks to generic). I already initiated sth at [`pimalaya/core/start-tls`](https://github.com/pimalaya/core/tree/master/start-tls), it could be a good starting point.

**Comment by duesee** [comment]
> This should not be part of imap-next in my opinion, especially since TLS is out of its scope 

Do you mean the do_starttls_prefix or also the `without_greeting` part? I would proceed here with the bare minimum, i.e., only provide a way to skip the greeting. The do_starttls_prefix was only for explanation purposes for now :-)

**Comment by soywod** [comment]
I would say both, in my opinion it's out of `imap-next` scope. It makes more sense for `imap-next` to expect a stream ready to use. Modification should be done outside of it. It fits better in higher level like `imap-client`, or even `email-lib`.

**Comment by duesee** [comment]
Yes, I agree. But: When you want to start a stream that was primed towards TLS, i.e., a connection that was brought up to the point where you can proceed as usual with TLS, the client must not expect a greeting. So... I think this needs to be implemented in imap-next. And the `without_greeting()` form seems to be the minimal interface required to uncouple from STARTTLS. Or do you see an alternative?

**Comment by soywod** [comment]
I dived into https://github.com/pimalaya/himalaya/issues/494#issuecomment-2495620971 and I understand now your proposition. Indeed `imap-next`'s client still awaits for the greeting, so we need a way to tell him not to handle it. I will propose a PR soon so we can discuss on it!
